import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import Header from "./components/Header";
import Footer from "./components/Footer";
 
// Font files can be colocated inside of `app`
const myFont = localFont({
  src: '../../public/fonts/NeueMontreal-Light.otf',
  display: 'swap',
})

 const bold = localFont({
  src: '../../public/fonts/NeueMontreal-Bold.otf',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Tolulope",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="bg-[#F4F7FA]" lang="en">
       <body className={myFont.className}>
       <Header/>

        <main  >{children}</main>
        <Footer/>

      </body>
    </html>
  )
}